### ISSUE TITLE
How to run the codes?

### ISSUE THREAD

**Issue by zc300** [davidtw0320/Resources-Allocation-in-The-Edge-Computing-Environment-Using-Reinforcement-Learning#1]
Hi,
Thanks for your contributions. When I try to run your codes, I find there is no 'KAIST' direction. So, how to get the data in 'KAIST' direction and run your codes? Many thanks.

**Comment by davidtw0320** [comment]
I have already uploaded the "KAIST" into the document. Please download the file and run the code again. Thank you for telling me the problem.

**Comment by RITUsulaam** [comment]
> I have already uploaded the "KAIST" into the document. Please download the file and run the code again. Thank you for telling me the problem.



heyy can u explain what exactly are the column names in KAIST mobility dataset  which u have used. I am having  a prob with that.
Thank you for the code it is helpful

**Comment by davidtw0320** [comment]
Hi,
In data/KAIST, the second column means the horizontal distance and the third column means the vertical distance according to a reference point. You may ignore the value in the first column.
